version: '3.4'

services:
  client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

