version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"


  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

